version: "3"
services:
  nginx:
    image: nginx:alpine
    restart: always
    container_name: ${APP_NAME}_nginx
    env_file:
      - .env
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/var/www
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      app-network:
        ipv4_address: 10.18.0.2

  php-fpm:
    build:
      context: .
      dockerfile: ./conf/php-fpm/Dockerfile
    restart: always
    container_name: ${APP_NAME}_php-fpm
    env_file:
      - .env
    tty: true
    volumes:
      - ./app:/var/www
      - ./conf/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      app-network:
        ipv4_address: 10.18.0.3

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.18.0.0/8
          # gateway: 10.18.0.1